name: venuevendor
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.6
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0
  flutter_secure_storage: ^9.2.1
  cupertino_icons: ^1.0.6
  uuid: ^4.4.0
  path_provider: ^2.1.3
  dartz: ^0.10.1
  flutter_riverpod: ^2.5.1

  json_annotation: ^4.4.0
  shared_preferences: ^2.2.3
  multi_select_flutter: ^4.1.3
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  awesome_dio_interceptor: ^1.2.0
  equatable: ^2.0.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  hive_flutter: ^1.1.0
  json_serializable: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10

  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/videos/


  # Uncomment if you have fonts to include
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
